### ISSUE TITLE
Can't import phaser3-drag-select

### ISSUE THREAD

**Issue by daneren2005** [amaccann/phaser3-plugins#51]
I tried to import the phaser3-drag-select module, and can't get it to work.  Just using

```
import DragSelectPlugin from '@pixelburp/phaser3-drag-select';
console.log(DragSelectPlugin);
```

logs DragSelectPlugin as undefined.  I also tried referencing the dist/phaser3-drag-select-plugin.js file directly and using require instead and all of them fail.  Is there something special you are doing when distributing the code which would break a standard webpack workflow?

**Comment by amaccann** [comment]
Apologies, the docs are wrong: use
```js
import {DragSelectPlugin} from '@pixelburp/phaser3-drag-select';
```

**Comment by daneren2005** [comment]
Doh, a lot of libraries require importing that way.  I'm not sure why I didn't think of trying that.  Thank you for the quick response!
